//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Participant
    {
        public int ParticipantID { get; set; }
        public string Roll_no { get; set; }
        public string email_id { get; set; }
        public Nullable<int> Application_id { get; set; }
        public string Scheduled_program_id { get; set; }
    
        public virtual ApplicationForm ApplicationForm { get; set; }
    }
}
