//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgramsOffered
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProgramsOffered()
        {
            this.ProgramsScheduleds = new HashSet<ProgramsScheduled>();
        }
    
        public string Program_Name { get; set; }
        public string Description { get; set; }
        public string Applicant_Eligibility { get; set; }
        public Nullable<int> Duration_in_years { get; set; }
        public string Degree_Certificate_Offered { get; set; }
        public int DummyID_PO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProgramsScheduled> ProgramsScheduleds { get; set; }
    }
}
