//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UASMiniProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Offer_Scheduled
    {
        public int DummyID_PO { get; set; }
        public Nullable<int> DummyID { get; set; }
    
        public virtual ProgramsScheduled ProgramsScheduled { get; set; }
        public virtual ProgramsOffered ProgramsOffered { get; set; }
    }
}
