//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UASMiniProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgramsScheduled
    {
        public string Scheduled_Program_Id { get; set; }
        public string Program_Name { get; set; }
        public string Location { get; set; }
        public Nullable<System.DateTime> Start_Date { get; set; }
        public Nullable<System.DateTime> End_Date { get; set; }
        public Nullable<int> Sessions_Per_Week { get; set; }
        public int DummyID { get; set; }
    
        public virtual Offer_Scheduled Offer_Scheduled { get; set; }
    }
}
